sequenceDiagram
    autonumber

    participant BTN as button
    participant MAIN as main
    participant NET as network
    participant CLOUD as cloud
    participant LOC as location
    participant PWR as power
    participant ENV as environmental
    participant STOR as storage
    participant FOTA as fota
    participant LED as led

    %% =========================
    %% Bootstrap / readiness
    %% =========================
    FOTA->>FOTA: FOTA_MODULE_READY
    FOTA->>MAIN: FOTA_MODULE_READY

    PWR->>PWR: POWER_MODULE_READY
    PWR->>MAIN: POWER_MODULE_READY
    PWR->>STOR: POWER_MODULE_READY

    LOC->>LOC: LOCATION_MODULE_READY
    LOC->>MAIN: LOCATION_MODULE_READY
    LOC->>CLOUD: LOCATION_MODULE_READY
    LOC->>STOR: LOCATION_MODULE_READY

    %% =========================
    %% User and timer triggers
    %% =========================
    BTN->>MAIN: BUTTON_PRESS_SHORT
    BTN->>MAIN: BUTTON_PRESS_LONG

    MAIN->>MAIN: TIMER_EXPIRED_SAMPLE_DATA
    MAIN->>MAIN: TIMER_EXPIRED_CLOUD
    MAIN->>MAIN: TIMER_CONFIG_CHANGED

    %% =========================
    %% Sampling flow
    %% =========================
    MAIN->>LOC: LOCATION_SEARCH_TRIGGER
    MAIN->>MAIN: LOCATION_SEARCH_TRIGGER
    MAIN->>CLOUD: LOCATION_SEARCH_TRIGGER
    MAIN->>STOR: LOCATION_SEARCH_TRIGGER

    LOC->>LOC: LOCATION_SEARCH_STARTED
    LOC->>MAIN: LOCATION_SEARCH_STARTED
    LOC->>CLOUD: LOCATION_SEARCH_STARTED
    LOC->>STOR: LOCATION_SEARCH_STARTED

    LOC->>LOC: LOCATION_SEARCH_DONE
    LOC->>MAIN: LOCATION_SEARCH_DONE
    LOC->>CLOUD: LOCATION_SEARCH_DONE
    LOC->>STOR: LOCATION_SEARCH_DONE

    MAIN->>PWR: POWER_BATTERY_PERCENTAGE_SAMPLE_REQUEST
    MAIN->>MAIN: POWER_BATTERY_PERCENTAGE_SAMPLE_REQUEST
    MAIN->>STOR: POWER_BATTERY_PERCENTAGE_SAMPLE_REQUEST

    PWR->>PWR: POWER_BATTERY_PERCENTAGE_SAMPLE_RESPONSE
    PWR->>MAIN: POWER_BATTERY_PERCENTAGE_SAMPLE_RESPONSE
    PWR->>STOR: POWER_BATTERY_PERCENTAGE_SAMPLE_RESPONSE

    MAIN->>ENV: ENVIRONMENTAL_SENSOR_SAMPLE_REQUEST
    MAIN->>STOR: ENVIRONMENTAL_SENSOR_SAMPLE_REQUEST

    ENV->>ENV: ENVIRONMENTAL_SENSOR_SAMPLE_RESPONSE
    ENV->>STOR: ENVIRONMENTAL_SENSOR_SAMPLE_RESPONSE

    %% =========================
    %% Location-cloud side flows
    %% =========================
    LOC->>LOC: LOCATION_CLOUD_REQUEST
    LOC->>MAIN: LOCATION_CLOUD_REQUEST
    LOC->>CLOUD: LOCATION_CLOUD_REQUEST
    LOC->>STOR: LOCATION_CLOUD_REQUEST

    LOC->>LOC: LOCATION_AGNSS_REQUEST
    LOC->>MAIN: LOCATION_AGNSS_REQUEST
    LOC->>CLOUD: LOCATION_AGNSS_REQUEST
    LOC->>STOR: LOCATION_AGNSS_REQUEST

    LOC->>LOC: LOCATION_GNSS_DATA
    LOC->>MAIN: LOCATION_GNSS_DATA
    LOC->>CLOUD: LOCATION_GNSS_DATA
    LOC->>STOR: LOCATION_GNSS_DATA

    CLOUD->>LOC: LOCATION_SEARCH_CANCEL
    CLOUD->>MAIN: LOCATION_SEARCH_CANCEL
    CLOUD->>CLOUD: LOCATION_SEARCH_CANCEL
    CLOUD->>STOR: LOCATION_SEARCH_CANCEL

    %% =========================
    %% Storage threshold / send flow
    %% =========================
    STOR->>STOR: STORAGE_THRESHOLD_REACHED
    STOR->>MAIN: STORAGE_THRESHOLD_REACHED
    STOR->>CLOUD: STORAGE_THRESHOLD_REACHED

    MAIN->>STOR: STORAGE_BATCH_REQUEST
    MAIN->>MAIN: STORAGE_BATCH_REQUEST
    MAIN->>CLOUD: STORAGE_BATCH_REQUEST

    CLOUD->>STOR: STORAGE_BATCH_REQUEST
    CLOUD->>MAIN: STORAGE_BATCH_REQUEST
    CLOUD->>CLOUD: STORAGE_BATCH_REQUEST

    STOR->>STOR: STORAGE_BATCH_AVAILABLE
    STOR->>MAIN: STORAGE_BATCH_AVAILABLE
    STOR->>CLOUD: STORAGE_BATCH_AVAILABLE

    STOR->>STOR: STORAGE_BATCH_EMPTY
    STOR->>MAIN: STORAGE_BATCH_EMPTY
    STOR->>CLOUD: STORAGE_BATCH_EMPTY

    STOR->>STOR: STORAGE_BATCH_BUSY
    STOR->>MAIN: STORAGE_BATCH_BUSY
    STOR->>CLOUD: STORAGE_BATCH_BUSY

    STOR->>STOR: STORAGE_BATCH_ERROR
    STOR->>MAIN: STORAGE_BATCH_ERROR
    STOR->>CLOUD: STORAGE_BATCH_ERROR

    CLOUD->>STOR: STORAGE_BATCH_CLOSE
    CLOUD->>MAIN: STORAGE_BATCH_CLOSE
    CLOUD->>CLOUD: STORAGE_BATCH_CLOSE

    STOR->>STOR: STORAGE_BATCH_CLOSE
    STOR->>MAIN: STORAGE_BATCH_CLOSE
    STOR->>CLOUD: STORAGE_BATCH_CLOSE

    STOR->>CLOUD: STORAGE_DATA

    MAIN->>STOR: STORAGE_SET_THRESHOLD
    MAIN->>MAIN: STORAGE_SET_THRESHOLD
    MAIN->>CLOUD: STORAGE_SET_THRESHOLD

    MAIN->>STOR: STORAGE_CLEAR
    MAIN->>MAIN: STORAGE_CLEAR
    MAIN->>CLOUD: STORAGE_CLEAR

    %% =========================
    %% Cloud control / shadow
    %% =========================
    MAIN->>CLOUD: CLOUD_SHADOW_GET_DESIRED
    MAIN->>MAIN: CLOUD_SHADOW_GET_DESIRED

    MAIN->>CLOUD: CLOUD_SHADOW_GET_DELTA
    MAIN->>MAIN: CLOUD_SHADOW_GET_DELTA

    MAIN->>CLOUD: CLOUD_SHADOW_SET_REPORTED_CONFIG
    MAIN->>MAIN: CLOUD_SHADOW_SET_REPORTED_CONFIG

    MAIN->>CLOUD: CLOUD_SHADOW_UPDATE_REPORTED_CONFIG
    MAIN->>MAIN: CLOUD_SHADOW_UPDATE_REPORTED_CONFIG

    MAIN->>CLOUD: CLOUD_SHADOW_UPDATE_REPORTED_DEVICE
    MAIN->>MAIN: CLOUD_SHADOW_UPDATE_REPORTED_DEVICE

    MAIN->>CLOUD: CLOUD_PROVISIONING_REQUEST
    MAIN->>MAIN: CLOUD_PROVISIONING_REQUEST

    CLOUD->>CLOUD: CLOUD_CONNECTED
    CLOUD->>MAIN: CLOUD_CONNECTED

    CLOUD->>CLOUD: CLOUD_DISCONNECTED
    CLOUD->>MAIN: CLOUD_DISCONNECTED

    CLOUD->>CLOUD: CLOUD_SHADOW_RESPONSE_DESIRED
    CLOUD->>MAIN: CLOUD_SHADOW_RESPONSE_DESIRED

    CLOUD->>CLOUD: CLOUD_SHADOW_RESPONSE_DELTA
    CLOUD->>MAIN: CLOUD_SHADOW_RESPONSE_DELTA

    CLOUD->>CLOUD: CLOUD_SHADOW_RESPONSE_EMPTY_DESIRED
    CLOUD->>MAIN: CLOUD_SHADOW_RESPONSE_EMPTY_DESIRED

    CLOUD->>CLOUD: CLOUD_SHADOW_RESPONSE_EMPTY_DELTA
    CLOUD->>MAIN: CLOUD_SHADOW_RESPONSE_EMPTY_DELTA

    CLOUD->>CLOUD: CLOUD_PROVISIONED
    CLOUD->>MAIN: CLOUD_PROVISIONED

    %% =========================
    %% Network events
    %% =========================
    MAIN->>NET: NETWORK_DISCONNECT
    MAIN->>MAIN: NETWORK_DISCONNECT
    MAIN->>CLOUD: NETWORK_DISCONNECT

    CLOUD->>NET: NETWORK_DISCONNECT
    CLOUD->>MAIN: NETWORK_DISCONNECT
    CLOUD->>CLOUD: NETWORK_DISCONNECT

    CLOUD->>NET: NETWORK_CONNECT
    CLOUD->>MAIN: NETWORK_CONNECT
    CLOUD->>CLOUD: NETWORK_CONNECT

    NET->>NET: NETWORK_CONNECTED
    NET->>MAIN: NETWORK_CONNECTED
    NET->>CLOUD: NETWORK_CONNECTED

    NET->>NET: NETWORK_DISCONNECTED
    NET->>MAIN: NETWORK_DISCONNECTED
    NET->>CLOUD: NETWORK_DISCONNECTED

    NET->>NET: NETWORK_UICC_FAILURE
    NET->>MAIN: NETWORK_UICC_FAILURE
    NET->>CLOUD: NETWORK_UICC_FAILURE

    NET->>NET: NETWORK_ATTACH_REJECTED
    NET->>MAIN: NETWORK_ATTACH_REJECTED
    NET->>CLOUD: NETWORK_ATTACH_REJECTED

    NET->>NET: NETWORK_LIGHT_SEARCH_DONE
    NET->>MAIN: NETWORK_LIGHT_SEARCH_DONE
    NET->>CLOUD: NETWORK_LIGHT_SEARCH_DONE

    NET->>NET: NETWORK_SEARCH_DONE
    NET->>MAIN: NETWORK_SEARCH_DONE
    NET->>CLOUD: NETWORK_SEARCH_DONE

    NET->>NET: NETWORK_MODEM_RESET_LOOP
    NET->>MAIN: NETWORK_MODEM_RESET_LOOP
    NET->>CLOUD: NETWORK_MODEM_RESET_LOOP

    NET->>NET: NETWORK_PSM_PARAMS
    NET->>MAIN: NETWORK_PSM_PARAMS
    NET->>CLOUD: NETWORK_PSM_PARAMS

    NET->>NET: NETWORK_EDRX_PARAMS
    NET->>MAIN: NETWORK_EDRX_PARAMS
    NET->>CLOUD: NETWORK_EDRX_PARAMS

    NET->>NET: NETWORK_SYSTEM_MODE_RESPONSE
    NET->>MAIN: NETWORK_SYSTEM_MODE_RESPONSE
    NET->>CLOUD: NETWORK_SYSTEM_MODE_RESPONSE

    %% =========================
    %% FOTA flow
    %% =========================
    MAIN->>FOTA: FOTA_POLL_REQUEST
    MAIN->>MAIN: FOTA_POLL_REQUEST

    FOTA->>FOTA: FOTA_DOWNLOADING_UPDATE
    FOTA->>MAIN: FOTA_DOWNLOADING_UPDATE

    FOTA->>FOTA: FOTA_IMAGE_APPLY_NEEDED
    FOTA->>MAIN: FOTA_IMAGE_APPLY_NEEDED

    MAIN->>FOTA: FOTA_IMAGE_APPLY
    MAIN->>MAIN: FOTA_IMAGE_APPLY

    FOTA->>FOTA: FOTA_SUCCESS_REBOOT_NEEDED
    FOTA->>MAIN: FOTA_SUCCESS_REBOOT_NEEDED

    FOTA->>FOTA: FOTA_DOWNLOAD_FAILED
    FOTA->>MAIN: FOTA_DOWNLOAD_FAILED

    FOTA->>FOTA: FOTA_DOWNLOAD_TIMED_OUT
    FOTA->>MAIN: FOTA_DOWNLOAD_TIMED_OUT

    FOTA->>FOTA: FOTA_DOWNLOAD_CANCELED
    FOTA->>MAIN: FOTA_DOWNLOAD_CANCELED

    FOTA->>FOTA: FOTA_DOWNLOAD_REJECTED
    FOTA->>MAIN: FOTA_DOWNLOAD_REJECTED

    %% =========================
    %% LED indications
    %% =========================
    MAIN->>LED: LED_RGB_SET